services:
  cms.admin.analytics.data:
    class: WebEtDesign\AnalyticsBundle\Block\Data
    arguments:
      - ~
      - '@templating'
      - '@analytics_api.service'
    tags:
      - { name: sonata.block }

  cms.admin.analytics.config:
    class: WebEtDesign\AnalyticsBundle\Block\Config
    arguments:
      - ~
      - '@templating'
      - '%wd_admin_analytics.map_key%'
      - '%wd_admin_analytics.view_names%'
      - '%wd_admin_analytics.view_ids%'
    tags:
      - { name: sonata.block }

  analytics_api.api:
    class: MediaFigaro\GoogleAnalyticsApi\Service\GoogleAnalyticsService
    arguments: ["%google_analytics_api.google_analytics_json_key%"]
    public: true

  WebEtDesign\AnalyticsBundle\Services\Analytics:
    arguments:
      - '@analytics_api.api'
      - '%wd_admin_analytics.view_ids%'

  analytics_api.service:
    alias: WebEtDesign\AnalyticsBundle\Services\Analytics
    public: true

  WebEtDesign\AnalyticsBundle\Controller\DataController:
    arguments:
      - '@analytics_api.service'
    tags: ['controller.service_arguments']

  WebEtDesign\AnalyticsBundle\Controller\UrlController:
    arguments:
      - '@analytics_api.service'
    tags: ['controller.service_arguments']

  WebEtDesign\AnalyticsBundle\Twig\ApiTwigExtension:
    public: true
    arguments:
      - '@analytics_api.service'
    tags:
      - { name: twig.extension }
