services:
  cms.admin.analytics.data:
    class: WebEtDesign\AnalyticsBundle\Block\Data
    autowire: true
    arguments:
      - 'Analytics Data Block'
      - '@templating'
      - '@analytics_api.service'
      - '@doctrine.orm.default_entity_manager'
      - '@security.helper'
      - '@session.flash_bag'
    tags:
      - { name: sonata.block }

  cms.admin.analytics.config:
    class: WebEtDesign\AnalyticsBundle\Block\Config
    arguments:
      - ~
      - '@templating'
      - '%wd_admin_analytics.map_key%'
      - '%wd_admin_analytics.view_names%'
      - '%wd_admin_analytics.view_ids%'
      - '@doctrine.orm.default_entity_manager'

    tags:
      - { name: sonata.block }

  analytics_api.api:
    class: MediaFigaro\GoogleAnalyticsApi\Service\GoogleAnalyticsService
    arguments: ["%google_analytics_api.google_analytics_json_key%"]
    public: true

  WebEtDesign\AnalyticsBundle\Services\Analytics:
    arguments:
      - '@analytics_api.api'
      - '@doctrine.orm.default_entity_manager'
      - '%wd_admin_analytics.view_ids%'

  analytics_api.service:
    alias: WebEtDesign\AnalyticsBundle\Services\Analytics
    public: true

  WebEtDesign\AnalyticsBundle\Controller\DataController:
    autowire: true
    arguments:
      - '@cache.app'
      - '@analytics_api.service'
      - '%env(GOOGLE_ANALYTICS_VIEW_ID)%'
    tags: ['controller.service_arguments']


  WebEtDesign\AnalyticsBundle\Twig\TwigExtension:
    public: true
    arguments:
      - '@analytics_api.service'
      - '@doctrine.orm.default_entity_manager'
      - '@service_container'
    tags:
      - { name: twig.extension }

  WebEtDesign\AnalyticsBundle\Repository\:
    resource: '../../Repository'
    autowire: true
    tags: ['doctrine.repository_service']
