services:
  cms.admin.analytics:
    class: WebEtDesign\AnalyticsBundle\Block\Base
    arguments:
      - ~
      - '@templating'
      - '@analytics_api.service'
    tags:
      - { name: sonata.block }
  analytics_api.api:
    class: MediaFigaro\GoogleAnalyticsApi\Service\GoogleAnalyticsService
    arguments: ["%google_analytics_api.google_analytics_json_key%"]
    public: true

  analytics_api.service:
    public: true
    class: WebEtDesign\AnalyticsBundle\Services\Analytics
    arguments:
      - '@analytics_api.api'
      - '%env(resolve:GOOGLE_ANALYTICS_VIEW_ID)%'
